### PR TITLE
Signup

### PR DESCRIPTION
**Pull request by akshaykadu24**
signup login and product page is done,
these three page linking also done

### CODE REVIEW

**Comment by akshaykadu24** [comment]
all done sign log product linking also

**Comment by Kunalyerunkar** [comment]
jh

**Review by Kunalyerunkar — APPROVED** [review]

**Comment by Kunalyerunkar** [comment]
h

**Comment by Kunalyerunkar** [comment]
h

**Comment by Kunalyerunkar** [comment]
h

**Comment by Kunalyerunkar** [comment]
h

**Review by Kunalyerunkar — APPROVED** [review]

**Pull request closed without merging**
